# pvc => PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个是指我 mysql 要用的东西
  name: webook-mysql-live-claim-v3
spec:
#   这个可以随便
  storageClassName: suibianv3
  accessModes:
#    一个人？一个线程？还是一个POD？还是一个数据库用户？读写
    - ReadWriteOnce
#    多个读，一个写
#    - ReadOnlyMany
#    - 多个读写
#    - ReadWriteMany
  resources:
    requests:
#      1 GB
      storage: 1Gi

  